### PR TITLE
Added the Windows Parameters "-nographics -batchmode" to the valheim-server script

### PR DESCRIPTION
**Pull request by Supportlik**
First of all: Great work!

I added the Windows Parameters "-nographics -batchmode" from the Steam Dedicated Server Package to the valheim-server script. 

This leads to 10% less CPU usage and less desync lag on my server.

### CODE REVIEW

**Comment by lloesche** [comment]
Thank you, LGTM.

**Review by lloesche — APPROVED** [review]

**Comment by InB4DevOps** [comment]
I updated my container to latest version but I don't see a change in CPU load at all. Neither in idle nor with players connected. Any idea?

**Comment by LHolst** [comment]
I can confirm a drop of 20%ish . Before 4cpu at 120%, after updating I'm running below 100% .

Great work!

**Comment by InB4DevOps** [comment]
I imagine the nographics switch only applies to systems that actually have a GPU. Since my NAS doesn't have a GPU that switch might not have an effect for me.

**Comment by lerb** [comment]
I've noticed a massive CPU-usage drop and a pretty hefty RAM-usage drop too since this was introduced. Docker used to show around 45% CPU usage and 2,5GB RAM usage, it's now down to 15% CPU/1,8GB RAM. I'm hosting on a Synology DS218+

Great work!

**Comment by lloesche** [comment]
@lerb that sounds more like you're experiencing the effects of server `v0.145.6` which had this in the changelog:
```
Dedicated server CPU usage fix (Framerate limiter)
```
Was released like two days ago or so and had that extreme CPU usage drop effect you're describing.

**Comment by lerb** [comment]
> @lerb that sounds more like you're experiencing the effects of server `v0.145.6` which had this in the changelog:
> 
> ```
> Dedicated server CPU usage fix (Framerate limiter)
> ```
> 
> Was released like two days ago or so and had that extreme CPU usage drop effect you're describing.
> 
> See https://store.steampowered.com/news/app/892970/old_view/3059603718045184990 for more details.

Oh, I see! Silly me, thank you for the clarification.

**Pull request merged**
