### PR TITLE
Initial BepInExPack mod support (Implements #282)

### PR DESCRIPTION
**Pull request by lloesche**
This PR unifies BepInEx mod support. It now supports installation and update of ValheimPlus and BepInExPack.

Plugins can be installed in `/config/bepinex/plugins/` for BepInExPack or `/config/valheimplus/plugins/` for ValheimPlus.

Config generation via ENV variables now works for `valheim_plus.cfg` and `BepInEx.cfg` as well as any other `.cfg` files via a `POST_BEPINEX_CONFIG_HOOK` event hook. The config generation tool has been renamed to `env2cfg`.

Please test this PR at `lloesche/valheim-server:dev` and provide feedback below or in #282.

### CODE REVIEW

**Comment by lloesche** [comment]
Thanks, fixed!

**Comment by thetaiter** [comment]
Will this add the ability to modify BepInEx.cfg values with env variables similar to what is currently supported for valheim_plus.cfg values?

**Comment by lloesche** [comment]
@thetaiter not sure. BepInEx uses sections with `.` in the name which is not an allowed env var character.
E.g.
```
[Logging.Console]
Enabled = false
```
Not sure how we would encode `Logging.Console`. We could of course come up with arbitrary rules like three underscore mean a dot, two underscore mean an underscore or something like that so that we would set `BEPINEXCFG_Logging___Console_Enable=false`. Not pretty but workable.

**Comment by lloesche** [comment]
@thetaiter the answer is now yes. In https://github.com/lloesche/valheim-server-docker/pull/288/commits/1ec2b5e771b7fea48692a00ecbf9d0c03ddc5920 I reworked the existing config generator and made it more universal. It can now generate/update arbitrary cfg files from env variables. Be it `BepInEx.cfg` or a plugins custom config file. There's also now a `PRE/POST_BEPINEX_CONFIG_HOOK` that allows you to call the config generator whenever BepInEx config is being generated or updated.

**Comment by thetaiter** [comment]
Amazing, thank you! Great work on this project, very impressive.

**Pull request merged**
