### PR TITLE
Adding Discord webhook for notification

### PR DESCRIPTION
**Pull request by santrancisco**
Thanks @lloesche for the awesome work! My friends and I found ourselves stranded in the middle of the sea when the server decided to do an update today so i modified the container a little to give us 5 minutes warning via discord server. It might be useful for others too?

### CODE REVIEW

**Comment by UhtredTheBold** [comment]
Wouldn't a better approach be for the server to wait until active connections are 0 and then perform the update?

**Comment by lloesche** [comment]
@santrancisco thank you for this PR! I think the idea of performing an action like notifying on Discord before a restart occurs is great!

I am however wary of any particular implementation as I don't want to end up in a situation where we have a `DISCORD_WEBHOOK`, `SLACK_WEBHOOK`, `PAGERDUTY_WEBHOOK`, `TEAMSPEAK_WEBHOOK`, `SKYPE_WEBHOOK`, `WHATSAPP_WEBHOOK`, ` and have to maintain all of them. You get my drift.

Instead I've started implementing event hooks. Like `POST_BACKUP_HOOK` that allows you to run a command that'll e.g. copy the created backup file to an S3 bucket.

Today we landed a PR #150 that adds additional event hooks for you to use. The ones relevant for you would be:

| Name | Default | Purpose |
|----------|----------|-------|
| `POST_BOOTSTRAP_HOOK` |  | Command to be executed after bootstrapping is done and before the server or any services are started. Can be used to install additional packages or perform additional system setup. Startup is blocked until this command returns. |
| `PRE_RESTART_HOOK` |  | Command to be executed before a server restart is performed. Current restart is blocked until this command returns. |

**Comment by lloesche** [comment]
@UhtredTheBold depends on how your server is used. I like to have updates instantly the second they get released. A normal restart will shut down the server gracefully and save the world so I don't mind getting disconnected once or twice a week if I just happen to be online during a Valheim update. But I can totally see a use case where people want to finish whatever they are doing and hold back the update until they have disconnected. The new PRE/POST event hooks should allow you to do this.

**Comment by lloesche** [comment]
@santrancisco would you like to refactor your PR into a `.sh` script that we can ship in `contrib/`? Check https://github.com/lloesche/valheim-server-docker/blob/main/contrib/scp_backup_file.sh for an example.

**Comment by santrancisco** [comment]
Oh mate, PRE_RESTART_HOOK is definitely much more neat. I will get it in a bit later. Thanks again for the work @lloesche ! :)

**Comment by lloesche** [comment]
@UhtredTheBold I thought about it and I think your idea is better. Just merged #156 which makes it so by default the server only performs update checks when there are no players connected.

**Comment by santrancisco** [comment]
I agree that this is more desirable so I think we can close this pull request! I don't think there is much use for discord notification etc :wink: Thanks again for working on this and I definitely learnt some nice tricks to structure bootstrap and run scripts.

**Comment by lloesche** [comment]
@santrancisco Oh I actually meant that I think there is use for a Discord notification script. I liked your idea and script very much, I just didn't want to integrate it right into the core code. Instead there is a `contrib/` folder where such scripts can reside. They can then be called via mentioned hooks.

**Comment by Derekcde** [comment]
@lloesche  Hi, thanks again for your work, I come back to this discussion because I tried the msg technique on discord but I can't get it to work, unfortunately I really don't have a lot of docker knowledge, cmd linux.
I copied what was written in the docker page:

DISCORD_WEBHOOK = "https: //discord.com/api/webhooks/8171522530 ..."
DISCORD_MESSAGE = "Restarting Valheim server in one minute!"
PRE_RESTART_HOOK = 'curl -sfSL -X POST -H "Content-Type: application / json" -d "{\" username \ ": \" Valheim \ ", \" content \ ": \" $ DISCORD_MESSAGE \ "}" "$ DISCORD_WEBHOOK" && sleep 60 '

I use a Qnap NAS with Container Station

if I adapt it with my webhooks and my message I have an error:
2021-03-06 15:43:16 [31] (INFO) Running pre restart hook: 'curl -sfSL -X POST -H "Content-Type: application / json" -d "{\" username \ ": \ "NASDocker Server \", \ "content \": \ "$ DISCORD_MESSAGE_REBOOT \"} "" $ DISCORD_WEBHOOK "&& sleep 60 '
/ usr / local / bin / valheim-updater: line 144: curl -sfSL -X POST -H "Content-Type: application / json" -d "{\" username \ ": \" NASDocker server \ ", \" content \ ": \" $ DISCORD_MESSAGE_REBOOT \ "}" "$ DISCORD_WEBHOOK" && sleep 60: **No such file or directory**

i dont know what i'm doing wrong could you help me?
Thank you in advance.

**Pull request closed without merging**
