### PR TITLE
Fix server idle & server listening checks on crossplay-enabled servers

### LINKED ISSUE #521: valheim-status reports 0 players online with -crossplay, resulting in lack of backups
It seems like the player count isn't reported correctly (it's always 0) when crossplay is enabled, resulting in backups not being created due to "the server being idle".

https://github.com/lloesche/valheim-server-docker/blob/f47432bfcc9de4308cfe78346bbfa579dbe4317b/common#L155-L169

A potential temporary fix to get the backups working again is to set `SERVER_PUBLIC=false` which forces UDP packet counting logic.

It might be worth falling back to UDP packet counting when `-crossplay` flag is present unless there's a better solution.

### PR DESCRIPTION
**Pull request by recursiveGecko**
Resolves  #521, #515

### CODE REVIEW

**Review by foobarmeow — DISMISSED** [review]
I'm no maintainer but LGTM!

**Review by serpi90 — APPROVED** [review]

**Comment by lloesche** [comment]
Hey, thanks for the PR. Question, does this still work with servers that are not using crossplay and are not public? I remember vaguely that non-public servers only ever listen on 2456 and never bind the query ports.

**Comment by wcdanh2** [comment]
+1, This looks like a good solution.

**Review by lloesche — APPROVED** [review]
Perfect, thank you @recursiveGecko

**Pull request merged**
