### PR TITLE
WIP env test DO NOT MERGE

### PR DESCRIPTION
**Pull request by lloesche**

### CODE REVIEW

**Comment by lloesche** [comment]
@TheCatLady I'm trying to get some git commit hash info into the generated Docker image so it is easier for me to figure out which version of the container somebody is running.
On Dockerhub I get the following variables:
```
SOURCE_TYPE=git
SOURCE_URL=https://github.com/lloesche/valheim-server-docker.git
SOURCE_BRANCH=dev
```
But in Github Actions the environment is pretty empty except for `PATH` and `HOME` and whatever we specify ourselves nothing is set. Is there any way to have the name of the branch in an environment variable?

**Comment by TheCatLady** [comment]
> @TheCatLady I'm trying to get some git commit hash info into the generated Docker image so it is easier for me to figure out which version of the container somebody is running.
> On Dockerhub I get the following variables:
> 
> ```
> SOURCE_TYPE=git
> SOURCE_URL=https://github.com/lloesche/valheim-server-docker.git
> SOURCE_BRANCH=dev
> ```
> 
> But in Github Actions the environment is pretty empty except for `PATH` and `HOME` and whatever we specify ourselves nothing is set. Is there any way to have the name of the branch in an environment variable?

Yes, we do this in another repo I contribute to, where we write the commit tag to a file. Where do you want the commit tag?  I can PR the necessary changes.

We can also tag the Docker image with the hash (in addition to `latest`).

**Comment by lloesche** [comment]
So my plan was to have these env variables, esp. `SOURCE_URL` and `SOURCE_BRANCH`. Where for source URL I could even use a default, so the branch really is all I need and then I'd use the `build-env` which already has `git` installed to fetch `git rev-parse HEAD` write probably somewhere to `/usr/local/etc/git-repo.HEAD`.

**Comment by TheCatLady** [comment]
> So my plan was to have these env variables, esp. `SOURCE_URL` and `SOURCE_BRANCH`. Where for source URL I could even use a default, so the branch really is all I need and then I'd use the `build-env` which already has `git` installed to fetch `git rev-parse HEAD` write probably somewhere to `/usr/local/etc/git-repo.HEAD`.

Yeah I can PR that shortly! And I can also put the hash in an env var, so you only need to use `git` to fetch the commit hash if it's unknown.

**Comment by lloesche** [comment]
Awesome! Thank you!

**Pull request closed without merging**
