### PR TITLE
fix the URL of the Thunderstore.io API call to get BepInExPack (fixes #665)

### LINKED ISSUE #665: "Bepinex updater" doesn't work
When setting `BEPINEX=true` server startup fails  
```
supervisord: valheim-updater DEBUG - [38] - BepInEx is enabled - running updater
supervisord: valheim-updater curl: (22) The requested URL returned error: 404 
supervisord: valheim-updater FATAL - Error: could not retrieve BepInEx release info from Thunderstore.io API
supervisord: valheim-updater ERROR - Failed to run BepInEx updater - retrying later - check your networking and volume access permissions
```

After some investigating, it turns out this is because it calls `https://valheim.thunderstore.io/api/experimental/package/denikson/BepInExPack_Valheim/` which doesn't work anymore, `https://thunderstore.io/api/experimental/package/denikson/BepInExPack_Valheim/` works (just removing the valheim subdomain)  

I'll try making this change locally and I'll submit a PR if it fixes the issue.

### PR DESCRIPTION
**Pull request by a-sala7**
Edit:
For a temporary manual fix until this PR is merged and the image is updated, please check @erNail's comment here 
https://github.com/lloesche/valheim-server-docker/pull/666#issuecomment-2028473407

### CODE REVIEW

**Review by alx377 — COMMENTED** [review]
Checked that this works.

**Comment by corbin-lounsbury** [comment]
I have nothing meaningful to contribute other than to point out this is the "PR of the Beast" (#666) :P

**Review by ivanv — APPROVED** [review]
I had the same error. If I make a manual adjustment in docker container, according to the uploaded patch, the problem is solved.

**Comment by Kiaos** [comment]
Yea i changed the url to https://thunderstore.io/api/experimental/package/denikson/BepInExPack_Valheim/ using vim and now my server works again.

**Review by Kiaos — APPROVED** [review]
After changing this in my own server it worked. So this is the solution..

**Comment by andrewshpyh** [comment]
Guys, can You push this merge to prod? I`m using CasaOS to run the server, changed link via nano, but still server stuck on this error, even after restarts of container\server.

**Review by andrewshpyh — APPROVED** [review]

**Comment by corbin-lounsbury** [comment]
> Guys, can You push this commit to prod? I`m using CasaOS to run the server, changed link via nano, but still server stuck on this error, even after restarts of container\server.

As a workaround, you could pull the repo down locally, make the changes, and run `docker build`. It would give you a working version until the main repo is updated. All you would need to do is switch the image source.

**Review by michaelmurfy — APPROVED** [review]
Tested and this works.

**Review by dvudd — APPROVED** [review]
I've also tested this and it works.

**Comment by TheStig022** [comment]
Please tell me in more detail how I can change the address? I can’t get access to BepInEx updater

**Comment by SenzuDuck** [comment]
> Please tell me in more detail how I can change the address? I can’t get access to BepInEx updater
> 
> UPD. I figured it out, all I had to do was google a little and with 0 knowledge everything worked out :)

Can you please point me in the right direction? I'm struggling to figure this out, thanks.

**Comment by Tronceon** [comment]
I apparently can't google as I can't locate the updater file to modify. Any clues to get me down the right path?

**Comment by Seanzuwu** [comment]
> I apparently can't google as I can't locate the updater file to modify. Any clues to get me down the right path?

Hello! 

The file is located in - usr/local/bin

then use vim or whatever you have installed to edit the file, if you don't have vim installed on the container you can

apt-get update
apt-get install vim

firefox 28-03 1711626443

**Comment by Tronceon** [comment]
> > I apparently can't google as I can't locate the updater file to modify. Any clues to get me down the right path?
> 
> Hello!
> 
> The file is located in - usr/local/bin
> 
> then use vim or whatever you have installed to edit the file, if you don't have vim installed on the container you can
> 
> apt-get update apt-get install vim

Thank you for that info... I, in my true noob self, was looking for the container files within my portainer install images instead of running the container console.....

Works like a charm now.

**Review by greentail-kitsune — APPROVED** [review]
It works. BepInExPack moved to new address https://thunderstore.io/api/experimental/package/denikson/BepInExPack_Valheim/

tested

**Review by Seanzuwu — APPROVED** [review]

**Comment by Kiaos** [comment]
is the maintainer gone or is he waiting till ashelands?

**Review by Klastic — APPROVED** [review]
lgtm

**Comment by erNail** [comment]
Can confirm that this fix works.
For anyone looking for a workaround until this Pull Request is merged:

1. Find the name/ID of your running `valheim-server` docker container 

    ```shell
    docker ps
    ```

1. Enter the filesystem of the running `valheim-server` docker container

    ```shell
    docker exec -it <VALHEIM_SERVER_CONTAINER_ID> /bin/bash
    ```

1. Open the file `usr/local/bin/bepinex-updater`:

    ```shell
    vi /usr/local/bin/bepinex-updater
    ```

1. Replace `https://valheim.thunderstore.io/api/experimental/package/denikson/BepInExPack_Valheim/` with `https://thunderstore.io/api/experimental/package/denikson/BepInExPack_Valheim/`
1. Wait until the docker container tries to access the BepInEx URL again (I am not sure if this happens with the file change, or in regular interval)

**Comment by a-sala7** [comment]
Thanks a lot @erNail, been wanting to write that but I was too lazy to be honest 😄

I'd like to add a bit of clarification on 4 and 5.

4. **To edit the url** for utter vi/vim noobs such as myself, to fix the url you're gonna want to move the cursor to stand right before the "valheim" word and press D and then W twice (short for "delete word") to remove "valheim" and the dot from the url. Then write :wq and enter to save your changes.
5. You'll just have to restart the container with `docker restart <VALHEIM_SERVER_CONTAINER_ID>`, for me the container simply sat idle and didn't do anything forever after encountering the bepinex url error.

Happy gaming

**Comment by russwe** [comment]
https://github.com/users/russwe/packages/container/valheim-server-docker

If you just need to pull a container and be done.  More than happy to MR some of the changes/tweaks back if desired, and quite happy to shut mine down once the fix is in ^_^

**Comment by aCursedComrade** [comment]
Bumping for attention, can confirm this PR fixes the `bepinex-updater` issues

**Comment by clarkent86** [comment]
Also confirming it works!

I built this and pushed it to my docker hub if anyone wants to use it: clarkent86/valheim-server

**Comment by Mathiasduc** [comment]
Can a reviewer have a quick look at this PR ?

**Review by NickDJM — APPROVED** [review]
Can confirm this solved me issue

**Review by Mathiasduc — APPROVED** [review]

**Comment by Kiaos** [comment]
I see him committing stuff on other things Not sure he cares about this project. He needs another reviewer incase something happens to him.

**Review by lloesche — APPROVED** [review]

**Comment by lloesche** [comment]
Hey, sorry for the late reply. I haven't played Valheim in over a year, so rarely check here. There are four other collaborators with commit access on this repo, but I guess they're in the same boat.

I'm open to adding additional active collaborators. Let me know if you have a good understanding of the components this repo is made up of (Docker, Go, Python, Bash) and I'll add you.

Again sorry for the delay.

**Comment by a-sala7** [comment]
@lloesche of course man it's totally understandable, no worries. 
I'd honestly offer to join but I'm absolutely abysmal at the black magic that is Bash and "meh" at Go. 😂
Best of luck and thanks again for this image.

**Comment by Mathiasduc** [comment]
Thanks 👍

**Pull request merged**
