### PR TITLE
Setting SERVER_PASS to empty value when VPLUS PW is disabled

### PR DESCRIPTION
**Pull request by JackTheFragger**
Fix for Issue #568

Setting SERVER_PASS to empty value if variable 'VPCFG_Server_disableServerPassword' is true

### CODE REVIEW

**Review by lloesche — CHANGES_REQUESTED** [review]
shellcheck is complaining about accessing `VPCFG_Server_disableServerPassword` without defining it.

You could reduce the code to something like:

```
SERVER_PASS=${SERVER_PASS-secret}
if [ "${VPCFG_Server_disableServerPassword:-}" = true ]; then
	SERVER_PASS=""
fi
```

**Comment by lloesche** [comment]
@JackTheFragger thank you for the PR! I added a comment to the code above.

**Comment by JackTheFragger** [comment]
> shellcheck is complaining about accessing `VPCFG_Server_disableServerPassword` without defining it.
> 
> You could reduce the code to something like:
> 
> ```
> SERVER_PASS=${SERVER_PASS-secret}
> if [ "${VPCFG_Server_disableServerPassword:-}" = true ]; then
> 	SERVER_PASS=""
> fi
> ```

Where do I define it?

**Comment by lloesche** [comment]
In `defaults`. At the same point where you made the current changes.

**Pull request merged**
